language:
  java

addons:
  sonarcloud:
    organization: "mazen-alasali-cu"
    token:
      secure: "**************************" # encrypted value of your token

before_install:
  - chmod +x build.sh

script:
  - ./build.sh

after_success:
  #Generating Site
  - travis_wait mvn site
  - bash <(curl -s https://codecov.io/bash)
  # SonarCloud
  # the following command line builds the project, runs the tests with coverage
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
